In [1]:
import torch
device= 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [2]:
with open(r"C:\Users\amogh\Downloads\wizard_of_oz.txt", 'r', encoding= 'utf-8') as f:
    text= f.read()

chars= sorted(set(text))
vocab_size= len(chars)
print(chars)

          

['\n', ' ', '!', '"', '&', "'", '(', ')', '*', ',', '-', '.', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', ']', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '\ufeff']


Now we create a tokeniser, to convert each element of the chars array to an integer.

In [3]:
string_to_int= {ch:i for i, ch in enumerate(chars) }
int_to_string= {i:ch for i, ch in enumerate(chars)}
encode= lambda s: [string_to_int[c] for c in s]
decode= lambda l: ''.join(int_to_string[i] for i in l)
#This is a very simple mapping for a small vocabulary


A bigram language model is called so, because it predicts a character based on the previous character.

Example:
Input string= hello

start->h

h->e

e->l

l->l

l->o

The prediction shall be made on the basis of the probability of succeeding characters, as determined by studying the corpus
. 

In [4]:
data= torch.tensor(encode(text), dtype= torch.long)

In [5]:
data[:100]

tensor([80,  1,  1, 28, 39, 42, 39, 44, 32, 49,  1, 25, 38, 28,  1, 44, 32, 29,
         1, 47, 33, 50, 25, 42, 28,  1, 33, 38,  1, 39, 50,  0,  0,  1,  1, 26,
        49,  0,  0,  1,  1, 36, 11,  1, 30, 42, 25, 38, 35,  1, 26, 25, 45, 37,
         0,  0,  1,  1, 25, 45, 44, 32, 39, 42,  1, 39, 30,  1, 44, 32, 29,  1,
        47, 33, 50, 25, 42, 28,  1, 39, 30,  1, 39, 50,  9,  1, 44, 32, 29,  1,
        36, 25, 38, 28,  1, 39, 30,  1, 39, 50])

In [6]:
n= int(0.71*len(data))
train_data= data[:n]
val_data= data[n:]



block_size= 8
batch_size= 4

def get_batch(split):
    if split== 'train':
        data= train_data
    else: data= val_data
    ix= torch.randint(len(data)-block_size, (batch_size, ))
    print(ix)
    x= torch.stack([data[i:i+block_size] for i in ix])
    y= torch.stack([data[i+1:i+block_size+1] for i in ix])
    x,y= x.to(device), y.to(device)
    return x,y
    
x,y= get_batch('train')

print('inputs')
print(x)
print('targets')
print(y)

tensor([ 84652, 141886, 133872,  41450])
inputs
tensor([[ 1, 72, 69, 65, 58, 67, 57, 62],
        [67, 57, 23,  1, 76, 58,  1, 76],
        [11,  3,  0,  0, 44, 61, 58,  1],
        [ 1, 76, 54, 73, 56, 61, 58, 57]], device='cuda:0')
targets
tensor([[72, 69, 65, 58, 67, 57, 62, 57],
        [57, 23,  1, 76, 58,  1, 76, 62],
        [ 3,  0,  0, 44, 61, 58,  1, 72],
        [76, 54, 73, 56, 61, 58, 57,  1]], device='cuda:0')


## Word Embedding

Embeddings are a means to convert words into tokens. These tokens are in the form of vectors/tensors. What is essential here is the knowledge of the vocabulary size, and a determination of the dimensions of the resultant vectors. 
An embedding layer is created using these as inputs; it is then used to look up/identify the embeddings for a given set of indices.

In [7]:
import torch.nn as nn
from torch.nn import functional as F



In [9]:
class BigramLanguageModel(nn.Module):
    #Define the Embedding table
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding_table= nn.Embedding(vocab_size, vocab_size)
    
    #Define the forward pass for the network
    def forward(self, index, targets= None):
        logits=self.token_embedding_table(index)
        #logits are of the form floating point numbers that have been normalised
        
        if targets is None:
            loss= None
        else:
            B, T, C= logits.shape
        #B is for Batches, T is for Targets, C is for 
            logits= logits.view(B*T,C)
            targets= targets.view(B*T)
            loss= F.cross_entropy(logits, targets)
        
        return logits, loss
    
    def generate(self, index, max_new_tokens):
        #index is (B,T) array of indices in current context (context as in context of tokens in the bigram) 
        for _ in range (max_new_tokens):
            logits,loss= self.forward(index) #gets predictions
            logits= logits[:,-1,:] #focussing on the last time step- property of the bigram, becomes (B,C)  
            probs= F.softmax(logits, dim= -1) # (B,C)
            
            index_next= torch.multinomial(probs, num_samples= 1)
            index= torch.cat((index, index_next), dim= 1) #for the new context
            
            return index
    
model= BigramLanguageModel(vocab_size)
m= model.to(device) 

context= torch.zeros((1,1), dtype= torch.long, device= device)
generated_chars= decode(m.generate(context, max_new_tokens= 500)[0].tolist())
print(generated_chars)


u


In [10]:
learning_rate= 4e-3
max_iters= 2000
optimiser= torch.optim.AdamW(model.parameters(), lr= learning_rate)

for iter in range(max_iters):
    
    xb, yb= get_batch('train')
    
    logits, loss= model.forward(xb, yb)
    optimiser.zero_grad(set_to_none= True)
    loss.backward()
    optimiser.step()
    
print(loss.item())
    

tensor([82187, 71844, 41144, 59979])
tensor([144778, 145625,  62812,  87832])
tensor([157798,  51877,  34135,  41527])
tensor([159753,  86237, 137522, 153757])
tensor([122213,  27762,  60657,  63538])
tensor([ 11982,  71612, 109037,  85797])
tensor([ 57095,  20850, 127442,  59530])
tensor([33417,  2412, 70043, 19100])
tensor([11958, 49188, 84214, 80465])
tensor([151922,  53187, 135742, 123676])
tensor([127081, 101331,  66838, 162339])
tensor([ 24454,   2666, 124781, 163175])
tensor([ 70134,  54448, 100784,  96322])
tensor([109052,  62976,  36360, 137511])
tensor([104671,  70708,  99698,  57759])
tensor([78228, 84964, 14374, 81841])
tensor([ 4653, 54683, 22357, 84565])
tensor([ 12036, 146858, 101509, 160893])
tensor([ 59513, 153795, 117720,  24833])
tensor([136765,  11954, 110240,  24293])
tensor([20196, 97181, 91872, 30786])
tensor([132530, 140769,   4656, 158324])
tensor([ 49130,  29967, 151399, 100959])
tensor([151105, 120401, 147924, 161761])
tensor([ 35612,  86047, 144884,  22752])

tensor([146059,  21603, 143300,  77177])
tensor([162851,  30343, 112095,  73548])
tensor([  1523, 128868, 163477,  38554])
tensor([ 67015,  14147, 149746,  62955])
tensor([  8304, 160337, 124540,   5018])
tensor([27712, 30544, 64647, 16232])
tensor([112422,  51219, 162354,  61644])
tensor([ 19696,   5798, 128638, 110945])
tensor([38933, 69323, 87701, 85530])
tensor([ 13406, 161945, 144584,  76022])
tensor([ 77461,  49705,  20861, 132487])
tensor([159595,  62562,  25856, 107042])
tensor([101300, 113290,  15224, 144777])
tensor([ 43235,  29476, 158208, 116023])
tensor([ 64414, 156078, 128100,  91070])
tensor([157235,  64196,    659,  59284])
tensor([ 86144, 132837, 160938,  36726])
tensor([122092,  23230, 149963, 143067])
tensor([113565,  89338,  58343,  82964])
tensor([ 16398,  26820, 145630, 130249])
tensor([161189,  71596, 141269, 142760])
tensor([ 31876,  83062,  40114, 146758])
tensor([115490,  36852,  75454,  72632])
tensor([ 64226, 140812,  34148, 148404])
tensor([120113, 136153, 

tensor([ 62738,  31122, 111945, 131249])
tensor([130383,  33883, 125747,  11906])
tensor([ 99824,  51521,  98469, 138575])
tensor([ 88466, 144053,  59619, 153039])
tensor([105939, 136842,  58897,  54782])
tensor([116018,  48120, 128180,  52138])
tensor([142678, 126308, 128946,   5829])
tensor([ 20292,  11151,  11149, 164643])
tensor([108933,  74372,   8704,   9519])
tensor([ 24852,  74799, 155361, 158869])
tensor([142270,  37970, 103237,  26656])
tensor([   485, 148392,  61088, 105036])
tensor([ 66999, 140243, 163636,  73725])
tensor([ 42433, 141041, 107374, 138296])
tensor([13281, 34648,  5663,  9736])
tensor([21031, 78035, 14021,  6994])
tensor([134466,  91071, 151059, 154279])
tensor([133900,  55217,   6636,  21647])
tensor([ 22995,  12976,  43167, 121015])
tensor([ 37088,  62586, 115769,  84369])
tensor([101603,  63891, 147756,  57009])
tensor([107189,  23851,  10717, 153688])
tensor([63630, 60472, 23196, 63917])
tensor([10166, 31976, 45966,  6910])
tensor([69577, 93903, 17512, 869

tensor([158618,  70854, 139108, 156032])
tensor([32956, 29660, 86164, 44070])
tensor([114359, 152676,  29183,  75072])
tensor([ 49814, 129923, 126869,  37334])
tensor([104322,  13618,  13013,  78607])
tensor([50263, 99000, 52229, 17689])
tensor([  1455,  96077, 134327,  52107])
tensor([117308, 162783,  31952,  81864])
tensor([ 99927, 115300,  15422, 153654])
tensor([158222,  77539,   1151,  81025])
tensor([ 13227, 155200, 123131, 118192])
tensor([ 95672, 115107,  91490,  47507])
tensor([143214,    536, 143280, 112529])
tensor([ 43162,  37205, 112354, 164425])
tensor([160238,  59069,  61151,  95188])
tensor([ 25830, 137020,  21001,  87906])
tensor([  6897,  80662, 157968, 143396])
tensor([  7036, 124822,  56412,  92570])
tensor([  5755,  87312,  54856, 149616])
tensor([152202,  15736,  15475,  18976])
tensor([ 53809, 106383, 113575,  14084])
tensor([ 61476,  47347, 114345, 145513])
tensor([32616, 44610, 30164, 63392])
tensor([ 95248, 163694, 141383,  90680])
tensor([140854,  33846,  304

tensor([134175, 152217, 139312,  75338])
tensor([151143,  42994,  81148,  77029])
tensor([ 36193,  22775, 139439,  54076])
tensor([157946, 113906,  55649,  70508])
tensor([ 80072,  75265, 125593,  72895])
tensor([128705, 125313, 162060, 111281])
tensor([ 74784, 133771,  33004,   4664])
tensor([ 16560, 141376,  36938,  33274])
tensor([88117, 39608, 23331, 59398])
tensor([116355,  10442,  46039,  59972])
tensor([ 76356, 113235,  66898, 143826])
tensor([111884, 143634,  30874,  84291])
tensor([150313, 140706, 132599, 110522])
tensor([119254,  98067,  59566,  22353])
tensor([135122, 132817,   8169,  63444])
tensor([ 30743, 110939, 158335,  19741])
tensor([80705, 69906, 32305, 46705])
tensor([ 80575,  65903, 158315,  98372])
tensor([ 58958, 150695,  94732, 152653])
tensor([ 62399, 121163,  60340, 146406])
tensor([95163, 97715, 92190, 34478])
tensor([127275,  21629,  38335, 120370])
tensor([161375, 110312,  65706, 151088])
tensor([130776,  83466, 120093, 128273])
tensor([ 17069, 151744,  882

tensor([150175,   8016, 117455,  38244])
tensor([164513, 122154,  96694,  29094])
tensor([98975, 34269, 83131,  3885])
tensor([119027, 135235,  84836,  33725])
tensor([ 15860, 124433, 135321,  12433])
tensor([150007,  96519, 128520,  79867])
tensor([ 89795,  11050, 150756, 118422])
tensor([107417, 158363,  53482,  46886])
tensor([81788, 82210, 96090, 60903])
tensor([103188, 131169, 102792,  11977])
tensor([115380, 102996, 158146,   3292])
tensor([119940,  42445, 131396, 147395])
tensor([ 28944, 115396, 159167,  13682])
tensor([ 88373,  36216,  27956, 110852])
tensor([ 50070,  83211, 122525, 161923])
tensor([160223,  88484,  30021,  46808])
tensor([44582, 25457, 49493, 97242])
tensor([ 93448,  65692, 109329,  26696])
tensor([61658,  6983, 18906, 91446])
tensor([138262, 100683,  50117,  56535])
tensor([120624, 141668,  42169,  90749])
tensor([146117, 107371, 155060, 107660])
tensor([41400, 84524, 35543, 65147])
tensor([103981, 160536, 143931,  11467])
tensor([146435, 118206,  17163, 1182

tensor([156577,  86589, 122727,  91985])
tensor([150008, 120210, 161544,  45942])
tensor([ 50174, 100600,  45684,   3745])
tensor([ 37163,  15916,  21177, 144353])
tensor([ 99010,  15719, 159244, 161467])
tensor([ 96041, 145141, 126422,  56074])
tensor([ 72089,  37340, 137479,   7750])
tensor([108520, 111806, 139051,  58586])
tensor([135636, 140438, 104045, 112942])
tensor([ 44407,  75187,  53032, 134362])
tensor([156637,  15058, 148306,  99438])
tensor([ 50029,  81764,  58198, 144580])
tensor([ 47175, 133570,  38982, 134333])
tensor([ 42059, 130823,  42426,  42348])
tensor([ 43796, 163321,  41608,  52184])
tensor([ 75406,   9919,  22778, 116153])
tensor([   913, 104157,  12650,  95160])
tensor([142899,  91975,  58056,  84210])
tensor([ 46559,  50202, 124304, 108213])
tensor([ 66128, 157615,  43033,  43193])
tensor([ 98981,  76234, 108875, 161493])
tensor([151452, 150400, 162005,  89197])
tensor([19247, 27175, 13200, 93210])
tensor([ 22421, 115310, 111130,  26942])
tensor([31231, 60085

tensor([147076, 134463, 105622,  22351])
tensor([ 91037,  95844, 121936,   7307])
tensor([137213,  97940,  56929, 101382])
tensor([  452, 48359, 93355, 19650])
tensor([110997,   3442, 158371,   6361])
tensor([143770,  96602,  55629, 144120])
tensor([149834,  90688, 153928,  46262])
tensor([ 18833,   1865,  62428, 145351])
tensor([134751, 121878,  45212, 140850])
tensor([ 73335,  89489, 132521,  68741])
tensor([57454,  5800, 45538, 94459])
tensor([137271, 126114, 156488, 129521])
tensor([155980, 109623,  17871,  58260])
tensor([ 9738, 56968, 61971, 66374])
tensor([78908, 10837, 92393, 53725])
tensor([101169,  66864,  35404, 147333])
tensor([119837,  34865, 161469,   5116])
tensor([125431,  41893,   1238,  28970])
tensor([111689, 123393,   9413,  44478])
tensor([ 96209, 163390, 108418, 103844])
tensor([135167,  87640,  88245,  10676])
tensor([ 78582, 164443,  45337,  41666])
tensor([  5085,   5250, 106449, 148187])
tensor([23379, 78064, 99054, 46103])
tensor([109131,  55668,  45226, 1008

tensor([ 22153, 112877, 136447,  91144])
tensor([155071,  80374,  39087,  86841])
tensor([158220, 157364, 101809, 128404])
tensor([ 85045, 132270, 140153,  30727])
tensor([156752, 139105,  57055,  88115])
tensor([ 52519, 124424,  19286, 108494])
tensor([ 90183,  50104, 128519, 161776])
tensor([109614,  26924, 145760, 159306])
tensor([ 19263, 119021, 100451,  14965])
tensor([ 68204,  99577,  82544, 120521])
tensor([130746,  94992, 100680,  62990])
tensor([18150, 35537, 30789, 45920])
tensor([144081, 121988,  60976,  68852])
tensor([ 97075,  98636, 135458,  72321])
tensor([ 65057, 117736,  39741, 114672])
tensor([ 73956,  75552, 157002,  20380])
tensor([ 23979,  36883, 112714, 134599])
tensor([31726, 53269, 41537, 94737])
tensor([38150, 30047, 94628, 32433])
tensor([131449,  28143,  12017,  35900])
tensor([151355, 145207,  91257, 131870])
tensor([  8084,  65529,  33546, 113408])
tensor([122426,  15218,  16190,  92462])
tensor([   675, 156385, 112979,  32880])
tensor([21962, 45145, 87657,

In [11]:
# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)
eval_iters= 200
@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

for iter in range(max_iters):
    if iter % eval_iters == 0:
        losses = estimate_loss()
        print(f"step: {iter}, train loss: {losses['train']:.3f}, val loss: {losses['val']:.3f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model.forward(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()
print(loss.item())

tensor([ 69615, 125058,  23915,   1259])
tensor([ 62591,  34459, 112393,  88475])
tensor([112550,   1224, 125318, 113735])
tensor([ 94278, 103785,  90637, 153469])
tensor([126381,  22819,  39475,  12352])
tensor([ 17376, 154345, 113198, 131942])
tensor([ 68211,  25031, 142543,   3545])
tensor([70283,  2708, 18121, 86406])
tensor([102556, 103123, 106523,  22529])
tensor([ 96620,   1010,  10298, 135931])
tensor([ 77403, 101917, 132540,  73981])
tensor([95113, 18323, 38653, 66484])
tensor([  7051, 126522, 153981,  38978])
tensor([133020, 157071, 113557,  51933])
tensor([126218,  84928, 147585,  72756])
tensor([  7999,  14115,  54464, 113881])
tensor([157483, 158397,  28703,  98747])
tensor([108127,  74153,  13535, 140633])
tensor([146992,  34805,  71954, 154594])
tensor([ 58565, 139690,  85360, 148091])
tensor([ 50253, 124432,   3637,  43188])
tensor([ 56966,  18236, 135070, 124913])
tensor([ 67815, 101637,  13847,  81481])
tensor([121794, 159825, 157211, 114953])
tensor([ 65062, 112556, 

tensor([58813, 45027, 20043, 13344])
tensor([43106, 11885, 43842, 26056])
tensor([15472, 34692,  1140, 10214])
tensor([51698,  6718, 65773, 37343])
tensor([14171, 63385, 15646, 62697])
tensor([41530, 25457,  9903, 65819])
tensor([ 1408,  3656,  1582, 36325])
tensor([24499,  7850, 30734, 49466])
tensor([54188, 45951,  1714, 59463])
tensor([63002,  5707, 11766, 39167])
tensor([ 6709, 26433, 44376,  8170])
tensor([27845, 43572, 21119, 44857])
tensor([ 1261, 19085, 47631, 16675])
tensor([10975, 33412, 29650, 36761])
tensor([53469, 33428, 20258, 19845])
tensor([63265,  6652, 10246, 36174])
tensor([19705, 48175, 44952, 49468])
tensor([30567, 33138, 17400, 18025])
tensor([39348, 65303, 24294,  6939])
tensor([15949, 33851, 12937, 14496])
tensor([31725, 17031, 43579, 32421])
tensor([ 7974, 64829, 44078, 51422])
tensor([63406, 17424, 48446, 50174])
tensor([22056, 10897, 47980, 20066])
tensor([49545, 36544, 18389, 64175])
tensor([55519,   750, 22900, 15950])
tensor([ 6898, 29794, 28259, 37117])
t

tensor([159788, 102712,  54571,  52159])
tensor([139066, 127105, 148160, 105950])
tensor([ 65057,   6522, 155834,  26493])
tensor([58674, 59391, 74652, 90929])
tensor([ 12717, 115796,     17, 132281])
tensor([ 74112, 121987,  45341,  90733])
tensor([102175, 146659,  41427,  49468])
tensor([ 67950, 111787,  93033, 101655])
tensor([138663, 118384, 146037, 129205])
tensor([ 35837, 149941,   7862,  91379])
tensor([ 72829, 123185, 105000,   9175])
tensor([ 61739,  32519, 151940, 148145])
tensor([ 45788,  17028, 107909,  28696])
tensor([ 58171, 148208,  27614,  51341])
tensor([ 82952,  78202,   2275, 144838])
tensor([135828, 140872,  92406,  77402])
tensor([ 55998,  25653, 107600, 130897])
tensor([41650, 70403, 86374, 74159])
tensor([155441, 141878,  60734, 129464])
tensor([110466, 123645,  69046,  71962])
tensor([ 55798,  26421, 151289, 145695])
tensor([ 75298,  97692,   2973, 135438])
tensor([85831, 73588, 84735, 68800])
tensor([ 86934, 113069, 124855,  24442])
tensor([133814, 126775, 1281

tensor([ 45727,  83904, 125556,  44181])
tensor([ 65092, 156211,  59723,  22390])
tensor([ 45208, 144075, 137692,  30823])
tensor([38249, 38851,  2271, 32251])
tensor([ 45511, 117417,  74258, 124053])
tensor([ 57776,  44727,  13218, 119153])
tensor([130634,  40320,  79423, 144850])
tensor([ 74129, 111727, 144745,  12058])
tensor([83343, 79804, 38762, 95614])
tensor([ 90736,  37216,  52703, 116259])
tensor([160133,  64886, 102091, 156504])
tensor([126759,  59487,  73140,  74175])
tensor([ 79381,  34271,  66312, 128288])
tensor([106284, 147119, 127761,  74682])
tensor([ 9721, 38747, 47110, 96864])
tensor([ 51577,  18910, 160884,  52083])
tensor([ 76278,  73530,  35791, 131308])
tensor([128101, 119337,  54737,  70400])
tensor([ 14272,  54940, 159668, 130589])
tensor([ 30050,  90537, 114666,  98858])
tensor([ 15369,  90355, 150600, 152945])
tensor([  8967,  60328, 105240, 133125])
tensor([ 72625,  97208, 129549, 139436])
tensor([ 86064, 118848,  13203,  72186])
tensor([115281, 120672, 1462

tensor([39192,  6556, 55156, 54658])
tensor([44531, 28212, 40435, 35710])
tensor([ 7237, 15737, 30647, 37310])
tensor([ 2754, 36213, 62060, 63389])
tensor([39611, 64416, 29022, 55669])
tensor([17568, 18511, 65317, 63261])
tensor([ 3396,  6026, 13283, 61595])
tensor([ 8748,  9037, 34353,   718])
tensor([24380, 28425, 11767, 23795])
tensor([30688, 24094,  7590,  3949])
tensor([17720, 60449,  3660, 46105])
tensor([49125, 39957, 47919, 10784])
tensor([23557,  3491, 36242, 29521])
tensor([13751, 14898, 11194, 40311])
tensor([24442, 60302, 22970,  6921])
tensor([10986, 29160, 54502, 25311])
tensor([47589, 50424, 32688, 37481])
tensor([66497, 17630, 25119, 14241])
tensor([ 8286, 16634, 17691, 45423])
tensor([16320, 60919, 41476, 47566])
tensor([13621, 33172, 49624, 28621])
tensor([25725, 40609, 32060, 66773])
tensor([38866, 26739, 19525,  2909])
tensor([ 9347, 31408, 31804, 22403])
tensor([14141, 42084, 12438, 63233])
tensor([23562, 31533, 55662, 10556])
tensor([25410, 41751, 48505,  2286])
t

tensor([13081, 22735,   606, 86783])
tensor([ 89168,  65435, 137978, 142369])
tensor([103018, 150365,  21878,  50612])
tensor([ 5243, 17421, 13410, 48741])
tensor([ 69348, 138375,  12110,  58918])
tensor([130303, 102236, 130424, 124449])
tensor([ 27584, 129111,  19200,  41196])
tensor([ 18795,  38055, 121870,  14006])
tensor([ 61908,  26822,  74578, 150534])
tensor([ 26363,  94196,   2415, 100727])
tensor([ 81703,  83739,  69942, 136759])
tensor([ 77872, 144228, 164066,  77280])
tensor([94293, 25245, 93007, 36514])
tensor([ 68340, 105278, 160259, 132871])
tensor([122471,  83657, 138357, 111701])
tensor([66468,   870, 50751, 85362])
tensor([33841, 64675, 92766, 62258])
tensor([156478,  55293,  89736,  78342])
tensor([102659,  26914, 106111, 139106])
tensor([121182, 163839,  14737,  38250])
tensor([ 78748, 119052,  66579, 151124])
tensor([ 79245,  20226,  90508, 129155])
tensor([ 35418, 129338, 107817,  75531])
tensor([139211,  14969, 118406,  89779])
tensor([66871, 44937, 28700, 41164])

tensor([22247, 13577, 36125, 45710])
tensor([24599, 59231, 36075,  4389])
tensor([28872, 18417, 56756, 57779])
tensor([18710, 20099, 59031, 29343])
tensor([ 3685, 30311, 35997, 14753])
tensor([55922, 52479, 17659, 37770])
tensor([62946,  8654, 53882, 29092])
tensor([34205,  9748, 39694, 26204])
tensor([51378, 50948, 50547, 53571])
tensor([26911, 65635, 11576, 16836])
tensor([11435, 60997, 31714, 66463])
tensor([25054, 31372, 64193, 65213])
tensor([24672, 20040, 39089, 54983])
tensor([20983,  7972, 38629, 10752])
tensor([58668, 36390, 67080, 21466])
tensor([22898, 60084, 40822, 23382])
tensor([36734, 45147,  8024, 24034])
tensor([ 6507, 58434, 25769, 63704])
tensor([ 4378, 36162, 37062, 34021])
tensor([12822, 42181, 62074, 36634])
tensor([50551, 21542,  2581, 29148])
tensor([48109, 38526, 59006, 58195])
tensor([65318, 11521, 29809, 32841])
tensor([37354, 55831, 64517, 14971])
tensor([37317,  4040, 67274, 28574])
tensor([56542, 50455, 59097, 13304])
tensor([30900, 23289, 38569, 32560])
t

tensor([ 69364, 154276,   8734,   7788])
tensor([136030, 105164,  85469, 142507])
tensor([ 46108, 150317,   3830, 163040])
tensor([ 97043, 108380,  22243,  51137])
tensor([150635,  63314,  15412, 152326])
tensor([80588, 94918,  9564, 64431])
tensor([ 64692,  22094, 152070, 106334])
tensor([111175,   1925,    939, 117965])
tensor([ 22012,  41056,  38572, 164170])
tensor([91011, 77125, 71293, 58511])
tensor([146494,   6289, 143220,  39049])
tensor([ 91482, 132401,  23050,  26696])
tensor([ 70917, 120028,  88698,  68513])
tensor([85173, 52669, 81975, 21692])
tensor([ 65404, 152835,  26433, 121886])
tensor([108274,  97266,  76275, 145249])
tensor([ 52421, 123133, 123980,  38024])
tensor([ 53383, 145058,  49615,  84466])
tensor([108775, 155598, 128828, 123718])
tensor([138546,  17532, 127819,  20996])
tensor([147936,   4214,  24179,  51527])
tensor([ 72415, 123390, 153718,  50063])
tensor([117166, 151881, 149641,  63586])
tensor([ 40984,  47920, 115006,  56099])
tensor([118454,   2940,  809

tensor([ 85703, 150277,  61868,   5643])
tensor([ 24579,  63712,  92891, 150006])
tensor([127085,  35145,  26029,   8828])
tensor([60778, 51341, 90585, 98610])
tensor([ 77733, 114980, 103614, 128516])
tensor([  6828, 135430,  11795,  96601])
tensor([32874, 17330, 79829, 68484])
tensor([62032, 13488, 27145, 84013])
tensor([157250,   2671,  97316, 129506])
tensor([ 97340,  55327, 154730,   7691])
tensor([101654, 102405, 137875, 111522])
tensor([148682,  67484, 120762,  80177])
tensor([  3493, 107367, 150231,  35591])
tensor([ 36362, 120039,  57551, 131303])
tensor([ 65350, 159069,  58113,  92902])
tensor([ 34939, 128890, 120418,  48966])
tensor([ 36783,  10226,  72176, 100001])
tensor([ 91880,  30840,  84715, 130695])
tensor([ 19814,  46174,  40838, 125485])
tensor([ 93722,  63912, 139943,  65076])
tensor([ 46796, 160360, 160188,  37153])
tensor([ 98290,  83928, 136591, 109085])
tensor([30814, 28652, 64004, 56162])
tensor([ 14110, 152764,  61313,  93364])
tensor([ 28544, 130796, 113590, 

tensor([ 62882,  10228,  35444, 144658])
tensor([ 27061, 145588,   8710,  34281])
tensor([156189,  84530, 119536,   1875])
tensor([ 88925,  50771, 143385,  81014])
tensor([111642,  70056,  27934,  41181])
tensor([119431,  92526,  71094,  69978])
tensor([ 73978,  86483,  80321, 136315])
tensor([112887, 143714, 105926,  62618])
tensor([ 22153,  79576, 124308,  86521])
tensor([ 14852,  60544,  59711, 106753])
tensor([   293,  89980,   7253, 108953])
tensor([ 38501, 104824, 111857,  56705])
tensor([  4996,  85555, 119481,  32221])
tensor([ 36468,  35996,  40723, 127866])
tensor([116630,  59561, 164536, 133329])
tensor([ 64173,  92476,  34928, 121196])
tensor([101518,  92286, 104008,   6193])
tensor([17215, 94732, 83922, 30687])
tensor([ 56079, 135271,  26838, 115174])
tensor([ 36989,  98587,  15384, 109055])
tensor([106308,  48091,  22877,  27924])
tensor([ 31923,  78171, 123443,  99118])
tensor([35646, 76693, 11762, 53463])
tensor([ 23895, 107132,  67417, 105553])
tensor([ 49118, 155051, 

tensor([110639, 159467,  29778,  68232])
tensor([ 73677, 127332,  52408,  45375])
tensor([86812, 61721, 84569, 56567])
tensor([ 14482,  94533, 109701, 132056])
tensor([ 59829, 100215,  11542, 147718])
tensor([119609,  63047,  83888,  41169])
tensor([99607, 58469, 44013, 54247])
tensor([111511, 151277, 154209,  46542])
tensor([ 62689,  93299, 105250,  81525])
tensor([ 39920, 106063,  74253,  80529])
tensor([ 37779,  31596,  29729, 152386])
tensor([ 78446,  86747, 145909,  50908])
tensor([ 34893, 133890,  71483,  85737])
tensor([125797, 156786, 129906, 140017])
tensor([162775, 106973, 143269, 115761])
tensor([  4642, 162719, 117320,   7861])
tensor([148022, 114885, 133763,  46984])
tensor([ 18846, 100480,  86284, 145616])
tensor([61233, 88166, 17240, 67986])
tensor([134792,  59071, 122355,  75042])
tensor([   706,  39058, 142848, 135194])
tensor([ 69920, 151447,  77592, 141690])
tensor([133766,  16134, 110812,  85989])
tensor([ 91554, 109503,  21227,  61341])
tensor([131576,  60992, 1286

tensor([17397,  2614, 63036, 57910])
tensor([21742, 59638, 13283, 50477])
tensor([49902, 65862, 14621, 12622])
tensor([23250, 49521, 49454,  7361])
tensor([26844,  7083, 45407, 35026])
tensor([10744,  1987, 21397, 23631])
tensor([52194,  4187, 41968, 28805])
tensor([29858, 14831,   729, 57150])
tensor([35720, 51695,  5565, 58089])
tensor([ 9478, 42641,  4150,  7632])
tensor([30571, 33132, 25171, 33658])
tensor([ 3276, 19765, 56322, 36803])
tensor([44435, 63836, 51053, 31691])
tensor([ 9362, 33663, 41393, 44100])
tensor([29636, 35217, 31836, 55670])
tensor([54005, 43001, 27187,  7748])
tensor([33954, 48902, 36968, 29899])
tensor([18716, 49313, 34407, 10538])
tensor([ 1629, 10877, 14897, 42876])
tensor([48831, 45996, 21833, 49229])
tensor([66930,  2941, 10455,  2310])
tensor([ 3350, 25161, 22565, 15782])
tensor([42858, 39820,  7933, 59905])
tensor([38825, 56203, 26841, 62558])
tensor([19422, 54195, 49976, 17608])
tensor([19036, 18689, 42042, 28034])
tensor([36726, 19310,  2795, 42643])
t

tensor([122316, 157062,  79327, 108795])
tensor([ 69911,  67433,   3523, 106819])
tensor([ 97830, 122933,  70037,  62813])
tensor([132493,  84670,  61088,  53429])
tensor([144449, 155934, 136735,   2063])
tensor([27642, 27487, 45733, 42550])
tensor([142048, 131792,  45113, 112512])
tensor([112539,  68279, 131335, 133197])
tensor([ 20353,  42022, 107461, 160800])
tensor([108167, 152996, 135374, 164347])
tensor([ 16984, 128733,   4264,  86946])
tensor([162753, 144879,  82751,  24518])
tensor([124326,  64316,  11203,  89131])
tensor([53761, 90229, 49654, 91862])
tensor([111576, 109780,  42238, 117498])
tensor([77697, 45389, 70493, 88976])
tensor([ 70615, 110838,  86812,   2858])
tensor([143858,  11914,  20499,  39456])
tensor([ 12492,  53570, 126828, 107101])
tensor([  4196, 126860,  13553, 161176])
tensor([137387, 111364,  68890, 107517])
tensor([114821,  99548,  23168,  72523])
tensor([ 88799, 113329,  40499, 119247])
tensor([ 38092,  91919, 118514, 134170])
tensor([119206, 118819, 1411

tensor([65319, 56533, 43653, 33642])
tensor([41307, 56659, 54651, 43251])
tensor([30822, 66476, 45808, 15718])
tensor([26547, 25019, 49801, 28109])
tensor([49710, 34691,  7101, 29391])
tensor([39474, 67162, 51986,  9490])
tensor([26507, 40707, 21160,  3527])
tensor([28913, 64512, 38787, 32721])
tensor([54865, 34542, 63337, 47771])
tensor([49573, 11694, 24725, 47976])
tensor([22444, 36347, 15337,   121])
tensor([56789, 11172, 11218, 47850])
tensor([39288, 27969, 53578, 67310])
tensor([15712, 44315, 43167, 63312])
tensor([53315, 35161, 36654, 47517])
tensor([42841, 35933, 51642, 20692])
tensor([39217, 13805, 62030, 31224])
tensor([52241, 31409, 54009, 43482])
tensor([60254, 21214, 25998,  2356])
tensor([ 4785, 42405, 20572, 60177])
tensor([30063, 15355, 23858, 52554])
tensor([28147, 64956, 33780, 38066])
tensor([  869, 41077, 35795, 22525])
tensor([38757, 35010, 53247, 12179])
tensor([ 6113, 46638, 62470,  5587])
tensor([19273, 28862, 57266, 31758])
tensor([23263, 64369, 25893, 16157])
t

tensor([108368,  39770,  94686,  80305])
tensor([131071, 105980,  48686, 133130])
tensor([138036, 123040,  76555, 152668])
tensor([ 10743, 137958,  40202,  92510])
tensor([ 64819, 133807,  38086,  77462])
tensor([136197, 137100, 108805,  61259])
tensor([68901,  5178, 97624, 18259])
tensor([ 83776, 164409,   9290,  18383])
tensor([ 61806,  64342, 123031,  68568])
tensor([ 12319,  91616,  29426, 124729])
tensor([116571, 106025,  34704,  43634])
tensor([126490, 152699, 151618,   3543])
tensor([51585,  4554, 62976, 25504])
tensor([67420, 40807, 45351, 70911])
tensor([147272, 128472,   8761,    691])
tensor([143913,  25064, 143940,  64387])
tensor([133382,  23272, 142944,  93474])
tensor([64073, 15755, 90070,  1021])
tensor([130470,  75425, 153114, 144575])
tensor([ 46567,  26192, 125093, 157026])
tensor([ 6960, 78182, 41295, 27677])
tensor([140848,  38933,  21250,  59533])
tensor([159585,  69262,  66486,  52253])
tensor([ 47606,  62288, 148421,  91003])
tensor([ 59626,  96422, 144954, 1029

tensor([ 48893, 137299,   7060,  69753])
tensor([ 78965, 130285, 146545, 139644])
tensor([ 55075,  31102, 153228,  69050])
tensor([ 98858, 116952,  37643, 107925])
tensor([ 90236,  74754, 103225,  86614])
tensor([ 66829, 138379,  50661,  22962])
tensor([ 59921,  87343, 132775, 151299])
tensor([103584, 122022, 163328, 102572])
tensor([ 20952, 127829, 149492, 116407])
tensor([46292, 31725, 65570,  4521])
tensor([111751, 105763, 144324,   1538])
tensor([ 58519, 130106,  40464,  10794])
tensor([158390,  48171,  56024, 132641])
tensor([152372, 146130,  32635, 102054])
tensor([135435,  41264,   1904,  24677])
tensor([ 93326, 147680, 151258, 142117])
tensor([ 73245, 117138, 103201, 116747])
tensor([124063,  65558,  40626,  38383])
tensor([134546, 148889, 147565, 163640])
tensor([ 86764,  44434,  67084, 150376])
tensor([ 39809,  91386,  71676, 162000])
tensor([142490,  13183, 125956,  99530])
tensor([ 15512,  92219, 122066,  35018])
tensor([ 48505,  63407, 149422, 140405])
tensor([138423, 1084

tensor([ 21372, 148580,  56870,  19773])
tensor([52177, 97188, 66545,  3576])
tensor([108163, 156082,  52998,  23360])
tensor([ 84775,  99046, 161656,  35774])
tensor([147535, 108536,   4327,  30911])
tensor([ 88623, 159206,  72305,   3647])
tensor([124059, 155147,  10046,  80996])
tensor([ 81370,  49068,   3536, 150045])
tensor([ 6781, 54494, 76133, 49256])
tensor([ 97112,  93315, 159507,  83899])
tensor([61263, 69452, 83779, 21182])
tensor([ 28572,  10145, 115622, 104164])
tensor([123887, 121076, 115094,  47765])
tensor([ 89561, 128421,  60871,   9330])
tensor([151005,  74220,  13068, 143208])
tensor([156495,  87483, 146285,  17181])
tensor([123549,  74577, 133794,  19183])
tensor([163052, 107320,  48852,  83166])
tensor([148862, 118501,  82943,  52908])
tensor([139057, 163242, 149207, 134118])
tensor([ 25800, 152640, 125188,  65886])
tensor([158873, 121520, 105543, 124109])
tensor([111576, 118127,  38860,  79759])
tensor([ 88245, 136624,  38784,  39670])
tensor([162268, 161556, 1279

tensor([  3765,  82028, 114289, 148184])
tensor([ 41301,  82277, 111519, 151712])
tensor([ 98920, 116480, 103270, 146906])
tensor([ 41323, 118093, 129583, 152539])
tensor([29007, 31370,  5946, 71595])
tensor([119194,  54098,  20988,  23748])
tensor([53020, 29389, 99418, 58202])
tensor([111968,   4570,  41280,  89813])
tensor([66224, 49560, 58813, 96856])
tensor([ 90012, 138829, 115900, 136175])
tensor([84435, 80757, 45580, 26256])
tensor([132519,  72704, 126255,    547])
tensor([117275, 150337,  84073, 109183])
tensor([ 56443,  89537,    255, 113197])
tensor([ 19801,  40050,  22875, 104926])
tensor([113954, 146511,  33251, 117428])
tensor([120172,  47009, 148949,  31516])
tensor([136286, 119534,  53868,  31936])
tensor([ 42415, 160184,  61591, 106492])
tensor([115823,  92638,  95998,  12534])
tensor([142969, 111726, 109915,  63399])
tensor([ 41404, 127569,  93345, 139721])
tensor([125658, 144362, 127921,  57649])
tensor([ 66430,  75273, 143573,  34595])
tensor([ 13957, 102368,  12403, 

tensor([ 23562, 118509,  32076, 155753])
tensor([136547, 160580,  51135,  23885])
tensor([ 10202, 108632,  30095,  93225])
tensor([163160,   9024,  35582, 137317])
tensor([47042, 16777, 62435, 41188])
tensor([ 22266, 113079,  52614, 124238])
tensor([105746,  53444,  77043, 133711])
tensor([127709, 136991,  60173,  18094])
tensor([ 22774, 153248,  60168,  70511])
tensor([153322,  50375,  91896, 134473])
tensor([127855, 108180,   6707,  65841])
tensor([  3944,  49091,  56029, 141701])
tensor([129760,  30657, 126149,  83510])
tensor([126161,  89043,  69307,  59334])
tensor([68383, 63743, 19102, 86225])
tensor([  529, 97915, 93861, 83922])
tensor([146873,  10888, 136060,   4666])
tensor([148641, 132217,  91750, 130747])
tensor([131801,  24732,  76311, 118086])
tensor([ 3033, 11241, 13679, 33493])
tensor([138417, 132595, 143144,  16981])
tensor([ 42663,  97070, 126710, 122226])
tensor([12537, 16562,   819, 13541])
tensor([111723, 125325, 131636,   2240])
tensor([102673,  77599,  20418, 1214

tensor([ 15592, 121823,  19933,  38325])
tensor([111208,  38932,  16211,  93923])
tensor([106020,  28051, 149209,  95285])
tensor([19119, 25535,  8229, 65469])
tensor([29293, 15850, 13703, 59875])
tensor([105499, 106500,  64152,  65609])
tensor([62362, 96223,   177, 74279])
tensor([161513,  18656,  27275, 161112])
tensor([ 51414,  38108, 106038, 139537])
tensor([  2687, 135619, 102529,  47039])
tensor([142354,  21972,  68395, 118378])
tensor([49406, 22500,  6859, 27967])
tensor([ 57003, 116129, 102339, 132394])
tensor([ 92707,  21819,   4263, 105219])
tensor([ 89424, 134007,  30555, 134994])
tensor([ 81488,  74275, 147634,   3373])
tensor([ 63287,  72578,   8600, 157072])
tensor([118666, 133640,  53070,  73471])
tensor([ 55176, 106546,  44091,  21145])
tensor([ 36990, 101445,  80651, 158681])
tensor([35773, 23279, 51612, 15838])
tensor([154510,  92548, 156903, 124461])
tensor([22587, 55298, 64623,  8722])
tensor([132581, 149507, 119975,  36349])
tensor([121860,  77910,  66754,  84368])

tensor([65176, 11125, 25682, 61242])
tensor([12992, 20616, 26383,   390])
tensor([41479, 12886, 12134, 56402])
tensor([61703, 14839, 57844, 35615])
tensor([29553, 12056, 24536, 66476])
tensor([ 9866, 23737, 10907, 35393])
tensor([41887,  1992, 21948, 25668])
tensor([19656, 35867, 45161, 45439])
tensor([  693,  2126, 17251, 56003])
tensor([44282, 57056,  3756, 44383])
tensor([55040, 64536,  9857, 43359])
tensor([27961, 17196, 22640, 46484])
tensor([24710, 46602, 42758, 50102])
tensor([66908, 62813, 18079, 36322])
tensor([63780, 37011, 54008, 54448])
tensor([16880,  6872, 47798, 18864])
tensor([44312, 12557, 18683, 63536])
tensor([50787,  2233, 25925, 29416])
tensor([31349, 61209,  5274, 44489])
tensor([15713, 34983, 21515, 49541])
tensor([42364, 54086,  7454, 13139])
tensor([43478, 30204, 32141, 18377])
tensor([56601, 18526,  7701, 42546])
tensor([43278, 51262, 63150, 39020])
tensor([27648, 47687, 34235, 10609])
tensor([25640, 16990, 66251, 22932])
tensor([36597, 48573, 50015, 64633])
t

tensor([ 13228, 160926,   9048,  40995])
tensor([125787,  52727, 131450, 159972])
tensor([131128, 103623,  16695, 121169])
tensor([ 94647,  48390, 144377,  77815])
tensor([141370,  81710,  95891, 122047])
tensor([ 50063, 152529, 158450,  10071])
tensor([37298, 45320, 41046, 49367])
tensor([  8914, 135756, 139345, 143612])
tensor([101094,  26911, 145571,  22731])
tensor([12364, 86558, 52851, 50119])
tensor([ 72010, 143956,    651, 147568])
tensor([162290, 100759, 146692, 110155])
tensor([110961,  72161,  62680,  90896])
tensor([ 12220, 142903, 128489,  69251])
tensor([164548, 106780,   7588,  57120])
tensor([143517,  89347,  97571,  39255])
tensor([ 42510,  58464, 151622, 108466])
tensor([136222,  85041, 107667,  57005])
tensor([ 26309, 144213, 118846,  74025])
tensor([ 50824,  85457, 116144, 143019])
tensor([147489,  58042, 103979, 113050])
tensor([ 65080,  64593, 151783,   2351])
tensor([ 97364, 139408, 102123, 160261])
tensor([127847, 109932, 132932, 102215])
tensor([67169, 70057, 64

tensor([35697, 33914, 51776, 29528])
tensor([60821, 35695, 47397, 19292])
tensor([11294, 64368, 40236,  2227])
tensor([28072,  4686, 58537, 60153])
tensor([34480, 62280,  2792,  5891])
tensor([17922, 64270, 52446, 45867])
tensor([21930, 33389, 63692, 31194])
tensor([11649, 21197, 48339,  4566])
tensor([48399, 23986, 41000, 30443])
tensor([58925, 23696, 38054, 24686])
tensor([ 6551, 20042, 61607, 40090])
tensor([ 6096,  1818, 19948, 49512])
tensor([38606, 26624,  8403, 59239])
tensor([62698, 54885, 36240, 36507])
tensor([ 8441, 63553, 17325, 28459])
tensor([31143, 22846,  6091, 40397])
tensor([11173, 45922, 14759, 47773])
tensor([10198, 32581,  7836, 34031])
tensor([44006, 40944, 40085, 15961])
tensor([30630, 65564,  3294, 43685])
tensor([60747, 14346,  3772,  6558])
tensor([ 2334, 59842, 26266, 33813])
tensor([47866, 52753, 29727, 55911])
tensor([ 2686, 61821, 38577,  8336])
tensor([12541,  6079, 11573, 40944])
tensor([ 4872, 14164,  2665, 40471])
tensor([57520,  3338,  1948, 57901])
t

In [14]:
context = torch.zeros((1,1), dtype=torch.long, device=device)
generated_chars = decode(m.generate(context, max_new_tokens=500)[0].tolist())
print(generated_chars)


"
